# Generated by Django 3.1a1 on 2020-05-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_house'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='House',
            new_name='Houses',
        ),
    ]
