# Generated by Django 3.1a1 on 2020-05-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20200523_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='image',
            field=models.URLField(default='https://img2.freepng.ru/20180520/qfl/kisspng-2d-computer-graphics-tile-based-video-game-buildin-5b02137bc384c6.3814977715268627158009.jpg'),
        ),
    ]
