# Generated by Django 3.1a1 on 2020-05-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20200527_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='geo',
            field=models.CharField(blank=True, default='Местоположение не указано', max_length=64, null=True),
        ),
    ]
