# Generated by Django 3.1a1 on 2020-05-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20200527_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='geo',
            field=models.CharField(default='Местоположение не указано', max_length=64),
        ),
        migrations.AlterField(
            model_name='houses',
            name='image',
            field=models.URLField(blank=True, default='https://img2.freepng.ru/20180520/qfl/kisspng-2d-computer-graphics-tile-based-video-game-buildin-5b02137bc384c6.3814977715268627158009.jpg'),
        ),
    ]
