# Generated by Django 3.1a1 on 2020-05-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_auto_20200527_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='average_price',
            field=models.IntegerField(default=2500000),
        ),
    ]
