# Generated by Django 3.1a1 on 2020-05-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_houses_average_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='average_price',
            field=models.IntegerField(default='2500000'),
        ),
    ]
