# Generated by Django 3.1.4 on 2020-12-15 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_houses_favourites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.TextField()),
                ('data_deposit', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.TextField()),
                ('name', models.TextField()),
                ('middle_name', models.TextField()),
                ('class_number', models.IntegerField()),
                ('letter', models.TextField()),
                ('pupil_marks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.marks')),
                ('pupil_pass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.pass')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField()),
                ('lesson_number', models.IntegerField()),
                ('class_number', models.IntegerField()),
                ('letter', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_subject', models.IntegerField()),
                ('name', models.TextField()),
                ('subject_homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='landing.homework')),
                ('subject_marks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.marks')),
                ('subject_schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_teacher', models.IntegerField()),
                ('surname', models.TextField()),
                ('name', models.TextField()),
                ('middle_name', models.TextField()),
                ('teacher_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('password', models.CharField(max_length=50)),
                ('login', models.TextField()),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='landing.pupil')),
                ('mod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='landing.teachers')),
            ],
        ),
        migrations.DeleteModel(
            name='Houses',
        ),
    ]
