# Generated by Django 3.2 on 2021-05-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
